### ISSUE TITLE
MiniShift or user OpenShift environment

### ISSUE THREAD

**Issue by rbaumgar** [redhatdemocentral/rhcs-destinasia-rules-demo#3]
If you are using MiniShift you need to import the templates from init.sh/.bat from https://github.com/redhatdemocentral/ocp-install-demo otherwise dotnet, fuse, ... ansible playbooks will fail...

oc login ... -u system:admin
oc create -n openshift -f 'https://raw.githubusercontent.com/redhat-developer/s2i-dotnetcore/master/dotnet_imagestreams.json'
oc create -n openshift -f 'https://raw.githubusercontent.com/jboss-openshift/application-templates/master/jboss-image-streams.json'
oc create -n openshift -f 'https://raw.githubusercontent.com/jboss-fuse/application-templates/master/fis-image-streams.json'
oc create -n openshift -f 'https://raw.githubusercontent.com/jboss-openshift/application-templates/master/eap/eap70-basic-s2i.json'
oc create -n openshift -f 'https://raw.githubusercontent.com/jboss-openshift/application-templates/master/decisionserver/decisionserver63-basic-s2i.json'

**Comment by eschabell** [comment]
Thanks for the tips, but this demo is not designed to support MiniShift. This is based on OpenShift Origin (community) vs OpenShift Container Platform (product).

Closing this for now, but nice reference for the Minishifters out there.
